//"Brother's Gift" "Soul Quenched" "Poisoned Faith" "A Chilling Wind" "Matryoshka" 

const baseTypes = JSON.stringify({
  'Abyss Jewels': [
    'Ghastly Eye Jewel',
    'Hypnotic Eye Jewel',
    'Murderous Eye Jewel',
    'Searching Eye Jewel',
  ],
  'Active Skill Gem': [
    'Animate Weapon',
    'Arctic Armour',
    'Artillery Ballista',
    'Barrage',
    'Bear Trap',
    'Blade Blast',
    'Blade Flurry',
    'Blade Vortex',
    'Bladefall',
    'Blast Rain',
    'Blink Arrow',
    'Blood Rage',
    'Burning Arrow',
    'Caustic Arrow',
    'Charged Dash',
    'Cobra Lash',
    'Cremation',
    'Cyclone',
    'Dash',
    'Desecrate',
    'Detonate Dead',
    'Double Strike',
    'Dual Strike',
    'Elemental Hit',
    'Ensnaring Arrow',
    'Ethereal Knives',
    'Explosive Arrow',
    'Explosive Trap',
    'Fire Trap',
    'Flamethrower Trap',
    'Flicker Strike',
    'Frenzy',
    'Frost Blades',
    'Galvanic Arrow',
    'Grace',
    'Haste',
    'Hatred',
    'Herald of Agony',
    'Herald of Ice',
    'Ice Shot',
    'Ice Trap',
    'Lacerate',
    'Lancing Steel',
    'Lightning Arrow',
    'Lightning Strike',
    'Mirror Arrow',
    'Pestilent Strike',
    'Phase Run',
    'Plague Bearer',
    "Poacher's Mark",
    'Precision',
    'Puncture',
    'Purity of Ice',
    'Rain of Arrows',
    'Reave',
    'Riposte',
    'Scourge Arrow',
    'Seismic Trap',
    'Shattering Steel',
    'Shrapnel Ballista',
    'Siege Ballista',
    'Smoke Mine',
    "Sniper's Mark",
    'Spectral Shield Throw',
    'Spectral Throw',
    'Split Arrow',
    'Splitting Steel',
    'Summon Ice Golem',
    'Temporal Chains',
    'Tornado Shot',
    'Toxic Rain',
    'Unearth',
    'Vaal Blade Vortex',
    'Vaal Burning Arrow',
    'Vaal Cyclone',
    'Vaal Detonate Dead',
    'Vaal Double Strike',
    'Vaal Grace',
    'Vaal Haste',
    'Vaal Impurity of Ice',
    'Vaal Lightning Strike',
    'Vaal Rain of Arrows',
    'Vaal Reave',
    'Vaal Spectral Throw',
    'Venom Gyre',
    'Viper Strike',
    'Volatile Dead',
    'Whirling Blades',
    'Wild Strike',
    'Withering Step',
    'Ancestral Cry',
    'Ancestral Protector',
    'Ancestral Warchief',
    'Anger',
    'Animate Guardian',
    'Berserk',
    'Bladestorm',
    'Blood and Sand',
    'Chain Hook',
    'Cleave',
    'Consecrated Path',
    'Decoy Totem',
    'Determination',
    'Devouring Totem',
    'Dominating Blow',
    'Dread Banner',
    'Earthquake',
    'Earthshatter',
    'Enduring Cry',
    'Exsanguinate',
    'Flesh and Stone',
    "General's Cry",
    'Glacial Hammer',
    'Ground Slam',
    'Heavy Strike',
    'Herald of Ash',
    'Herald of Purity',
    'Holy Flame Totem',
    'Ice Crash',
    'Immortal Call',
    'Infernal Blow',
    'Infernal Cry',
    'Intimidating Cry',
    'Leap Slam',
    'Molten Shell',
    'Molten Strike',
    'Perforate',
    'Petrified Blood',
    "Portal",
    'Pride',
    'Punishment',
    'Purity of Fire',
    'Rallying Cry',
    'Reap',
    'Reckoning',
    'Rejuvenation Totem',
    'Searing Bond',
    'Seismic Cry',
    'Shield Charge',
    'Shockwave Totem',
    'Smite',
    'Static Strike',
    'Steelskin',
    'Summon Flame Golem',
    'Summon Stone Golem',
    'Sunder',
    'Sweep',
    'Tectonic Slam',
    'Vaal Ancestral Warchief',
    'Vaal Earthquake',
    'Vaal Glacial Hammer',
    'Vaal Ground Slam',
    'Vaal Impurity of Fire',
    'Vaal Molten Shell',
    'Vengeance',
    'Vigilant Strike',
    'Vitality',
    'Vulnerability',
    'War Banner',
    "Warlord's Mark",
    'Arc',
    'Arcane Cloak',
    'Arcanist Brand',
    'Armageddon Brand',
    "Assassin's Mark",
    'Ball Lightning',
    'Bane',
    'Blazing Salvo',
    'Blight',
    'Bodyswap',
    'Bone Offering',
    'Brand Recall',
    'Clarity',
    'Cold Snap',
    'Conductivity',
    'Contagion',
    'Conversion Trap',
    'Convocation',
    'Crackling Lance',
    'Creeping Frost',
    'Dark Pact',
    'Despair',
    'Discharge',
    'Discipline',
    'Divine Ire',
    'Elemental Weakness',
    'Enfeeble',
    'Essence Drain',
    'Fireball',
    'Firestorm',
    'Flame Dash',
    'Flame Surge',
    'Flame Wall',
    'Flameblast',
    'Flammability',
    'Flesh Offering',
    'Freezing Pulse',
    'Frost Bomb',
    'Frost Shield',
    'Frost Wall',
    'Frostbite',
    'Frostblink',
    'Frostbolt',
    'Glacial Cascade',
    'Herald of Thunder',
    'Hexblast',
    'Hydrosphere',
    'Ice Nova',
    'Ice Spear',
    'Icicle Mine',
    'Incinerate',
    'Kinetic Blast',
    'Kinetic Bolt',
    'Lightning Spire Trap',
    'Lightning Tendrils',
    'Lightning Trap',
    'Lightning Warp',
    'Malevolence',
    'Orb of Storms',
    'Penance Brand',
    'Power Siphon',
    'Purifying Flame',
    'Purity of Elements',
    'Purity of Lightning',
    'Pyroclast Mine',
    'Raise Spectre',
    'Raise Zombie',
    'Righteous Fire',
    'Rolling Magma',
    'Scorching Ray',
    'Shock Nova',
    'Sigil of Power',
    'Siphoning Trap',
    'Soulrend',
    'Spark',
    'Spellslinger',
    'Spirit Offering',
    'Storm Brand',
    'Storm Burst',
    'Storm Call',
    'Stormbind',
    'Stormblast Mine',
    'Summon Carrion Golem',
    'Summon Chaos Golem',
    'Summon Holy Relic',
    'Summon Lightning Golem',
    'Summon Raging Spirit',
    'Summon Skeletons',
    'Summon Skitterbots',
    'Tempest Shield',
    'Vaal Arc',
    'Vaal Blight',
    "Vaal Breach",
    'Vaal Clarity',
    'Vaal Cold Snap',
    'Vaal Discipline',
    'Vaal Fireball',
    'Vaal Flameblast',
    'Vaal Ice Nova',
    'Vaal Impurity of Lightning',
    'Vaal Lightning Trap',
    'Vaal Power Siphon',
    'Vaal Righteous Fire',
    'Vaal Spark',
    'Vaal Storm Call',
    'Vaal Summon Skeletons',
    'Void Sphere',
    'Vortex',
    'Wave of Conviction',
    'Winter Orb',
    'Wintertide Brand',
    'Wither',
    'Wrath',
    'Zealotry',
  ],
  'Amulet': [
    'Coral Amulet',
    'Paua Amulet',
    'Amber Amulet',
    'Jade Amulet',
    'Lapis Amulet',
    'Gold Amulet',
    'Agate Amulet',
    'Citrine Amulet',
    'Turquoise Amulet',
    'Onyx Amulet',
    'Simplex Amulet',
    'Astrolabe Amulet',
    'Marble Amulet',
    'Seaglass Amulet',
    'Blue Pearl Amulet',
    'Talisman',
  ],
  'Atlas Upgrade Item': [],
  'Belt': [
    'Chain Belt',
    'Rustic Sash',
    'Stygian Vise',
    'Heavy Belt',
    'Leather Belt',
    'Cloth Belt',
    'Studded Belt',
    'Micro-Distillery Belt',
    'Mechalarm Belt',
    'Vanguard Belt',
    'Crystal Belt',
  ],
  "Blueprint": [],
  'Body Armour': [
    'Plate Vest',
    'Chestplate',
    'Copper Plate',
    'War Plate',
    'Full Plate',
    'Arena Plate',
    'Lordly Plate',
    'Bronze Plate',
    'Battle Plate',
    'Sun Plate',
    'Colosseum Plate',
    'Majestic Plate',
    'Golden Plate',
    'Crusader Plate',
    'Astral Plate',
    'Gladiator Plate',
    'Glorious Plate',
    'Shabby Jerkin',
    'Strapped Leather',
    'Buckskin Tunic',
    'Wild Leather',
    'Full Leather',
    'Sun Leather',
    "Thief's Garb",
    'Eelskin Tunic',
    'Frontier Leather',
    'Glorious Leather',
    'Coronal Leather',
    "Cutthroat's Garb",
    'Sharkskin Tunic',
    'Destiny Leather',
    'Exquisite Leather',
    'Zodiac Leather',
    "Assassin's Garb",
    'Simple Robe',
    'Silken Vest',
    "Scholar's Robe",
    'Silken Garb',
    "Mage's Vestment",
    'Silk Robe',
    'Cabalist Regalia',
    "Sage's Robe",
    'Silken Wrap',
    "Conjurer's Vestment",
    'Spidersilk Robe',
    'Destroyer Regalia',
    "Savant's Robe",
    'Necromancer Silks',
    "Occultist's Vestment",
    'Widowsilk Robe',
    'Vaal Regalia',
    'Scale Vest',
    'Light Brigandine',
    'Scale Doublet',
    'Infantry Brigandine',
    'Full Scale Armour',
    "Soldier's Brigandine",
    'Field Lamellar',
    'Wyrmscale Doublet',
    'Hussar Brigandine',
    'Full Wyrmscale',
    "Commander's Brigandine",
    'Battle Lamellar',
    'Dragonscale Doublet',
    'Desert Brigandine',
    'Full Dragonscale',
    "General's Brigandine",
    'Triumphant Lamellar',
    'Chainmail Vest',
    'Chainmail Tunic',
    'Ringmail Coat',
    'Chainmail Doublet',
    'Full Ringmail',
    'Full Chainmail',
    'Holy Chainmail',
    'Latticed Ringmail',
    'Crusader Chainmail',
    'Ornate Ringmail',
    'Chain Hauberk',
    'Devout Chainmail',
    'Loricated Ringmail',
    'Conquest Chainmail',
    'Elegant Ringmail',
    "Saint's Hauberk",
    'Saintly Chainmail',
    'Padded Vest',
    'Oiled Vest',
    'Padded Jacket',
    'Oiled Coat',
    'Scarlet Raiment',
    'Waxed Garb',
    'Bone Armour',
    'Quilted Jacket',
    'Sleek Coat',
    'Crimson Raiment',
    'Lacquered Garb',
    'Crypt Armour',
    'Sentinel Jacket',
    'Varnished Coat',
    'Blood Raiment',
    'Sadist Garb',
    'Carnal Armour',
    'Grasping Mail',
    'Sacrificial Garb',
  ],
  'Boots': [
    'Iron Greaves',
    'Steel Greaves',
    'Basemetal Treads',
    'Plated Greaves',
    'Reinforced Greaves',
    'Antique Greaves',
    'Ancient Greaves',
    'Darksteel Treads',
    'Goliath Greaves',
    'Vaal Greaves',
    'Titan Greaves',
    'Brimstone Treads',
    'Rawhide Boots',
    'Goathide Boots',
    'Cloudwhisper Boots',
    'Deerskin Boots',
    'Nubuck Boots',
    'Eelskin Boots',
    'Sharkskin Boots',
    'Windbreak Boots',
    'Shagreen Boots',
    'Stealth Boots',
    'Slink Boots',
    'Stormrider Boots',
    'Wool Shoes',
    'Velvet Slippers',
    'Duskwalk Slippers',
    'Silk Slippers',
    'Scholar Boots',
    'Satin Slippers',
    'Samite Slippers',
    'Nightwind Slippers',
    'Conjurer Boots',
    'Arcanist Slippers',
    'Sorcerer Boots',
    'Dreamquest Slippers',
    'Leatherscale Boots',
    'Ironscale Boots',
    'Bronzescale Boots',
    'Steelscale Boots',
    'Serpentscale Boots',
    'Wyrmscale Boots',
    'Hydrascale Boots',
    'Dragonscale Boots',
    'Two-Toned Boots',
    'Chain Boots',
    'Ringmail Boots',
    'Mesh Boots',
    'Riveted Boots',
    'Zealot Boots',
    'Soldier Boots',
    'Legion Boots',
    'Crusader Boots',
    'Two-Toned Boots',
    'Wrapped Boots',
    'Strapped Boots',
    'Clasped Boots',
    'Shackled Boots',
    'Trapper Boots',
    'Ambush Boots',
    'Carnal Boots',
    "Assassin's Boots",
    'Murder Boots',
    'Fugitive Boots',
    'Two-Toned Boots',
  ],
  'Bow': [
    'Crude Bow',
    'Short Bow',
    'Long Bow',
    'Composite Bow',
    'Recurve Bow',
    'Bone Bow',
    'Royal Bow',
    'Hedron Bow',
    'Death Bow',
    'Grove Bow',
    'Reflex Bow',
    'Decurve Bow',
    'Compound Bow',
    'Sniper Bow',
    'Ivory Bow',
    'Foundry Bow',
    'Highborn Bow',
    'Decimation Bow',
    'Thicket Bow',
    'Steelwood Bow',
    'Citadel Bow',
    'Assassin Bow',
    'Spine Bow',
    'Imperial Bow',
    'Harbinger Bow',
    'Solarine Bow',
    'Maraketh Bow',
  ],
  'Claw': [
    'Nailed Fist',
    'Sharktooth Claw',
    'Awl',
    "Cat's Paw",
    'Blinder',
    'Timeworn Claw',
    'Shadow Fangs',
    'Sparkling Claw',
    'Fright Claw',
    'Double Claw',
    'Thresher Claw',
    'Gouger',
    "Tiger's Paw",
    'Gut Ripper',
    'Prehistoric Claw',
    'Malign Fangs',
    'Noble Claw',
    'Eagle Claw',
    'Twin Claw',
    'Great White Claw',
    'Throat Stabber',
    "Hellion's Paw",
    'Eye Gouger',
    'Vaal Claw',
    'Imperial Claw',
    'Terror Claw',
    'Void Fangs',
    'Gemini Claw',
  ],
  "Contract": [],
  'Currency': [
    "Crystalline Geode",
    "Magmatic Ore",
    "Igneous Geode",
    "Tainted",
    "Divine Orb",
    "Tainted Divine Teardrop",
    "Tainted Exalted Orb",
    "Tainted Orb of Fusing",
    "Tainted Chaos Orb",
    "Eldritch Chaos Orb",
    "Essence of Insanity",
    "Essence of Horror",
    "Essence of Delirium",
    "Sacred Crystallised Lifeforce",
    "Essence of Hysteria",
    "Reflective Oil",
    "Tainted Mythic Orb",
    "Orb of Dominance",
    "Orb of Conflict",
    "Exceptional Eldritch Ichor",
    "Exceptional Eldritch Ember",
    "Sacred Orb",
    "Eldritch Orb of Annulment",
    "Fracturing Shard",
    "Flawless Breachstone",
    "Fracturing Orb",
    "Infused Engineer's Orb",
    "Deafening Essence of",
    "Remnant of Corruption",
    "Shrieking Essence of",
    "Facetor's Lens",
    "Crystallised Lifeforce",
    "Blessing of",
    "Specularity Scroll",
    "Haemocombustion Scroll",
    "Electroshock Scroll",
    "Deregulation Scroll",
    "Fragmentation Scroll",
    "Time-light Scroll",
    "Vial of",
    "Oil Extractor",
    "Recombinator",
    "Grand Eldritch Ember",
    "Grand Eldritch Ichor",
    "Crescent Splinter",
    "Orb of Horizons",
    "Delirium Orb",
    "Breachstone",
    "Screaming Essence of",
    "Wailing Essence of",
    "Weeping Essence of",
    "Fossil",
    "Catalyst",
    "Burial Medallion",
    "Astragali",
    "Scrap Metal",
    "Exotic Coinage",
    'Abrasive Catalyst',
    'Accelerating Catalyst',
    'Albino Rhoa Feather',
    "Armourer's Scrap",
    'Awakened Sextant',
    "Awakener's Orb",
    'Bestiary Orb',
    "Blacksmith's Whetstone",
    'Blessed Orb',
    'Blessing of Chayula',
    'Blessing of Esh',
    'Blessing of Tul',
    'Blessing of Uul-Netol',
    'Blessing of Xoph',
    "Cartographer's Chisel",
    'Chaos Orb',
    'Chromatic Orb',
    "Crusader's Exalted Orb",
    'Elevated Sextant',
    "Enkindling Orb",
    'Exalted Orb',
    'Fertile Catalyst',
    "Gemcutter's Prism",
    "Glassblower's Bauble",
    "Greater Eldritch Ember",
    "Greater Eldritch Ichor",
    "Hunter's Exalted Orb",
    'Imbued Catalyst',
    'Imprint',
    'Imprinted Bestiary Orb',
    'Instilling Orb',
    'Intrinsic Catalyst',
    "Jeweller's Orb",
    "Maven's Orb",
    'Mirror of Kalandra',
    "Muttering Essence of",
    'Noxious Catalyst',
    'Orb of Alchemy',
    'Orb of Alteration',
    'Orb of Annulment',
    'Orb of Augmentation',
    'Orb of Chance',
    'Orb of Fusing',
    'Orb of Regret',
    'Orb of Scouring',
    'Orb of Transmutation',
    'Orb of Unmaking',
    'Portal Scroll',
    'Prime Regrading Lens',
    'Prime Sextant',
    'Prismatic Catalyst',
    "Redeemer's Exalted Orb",
    'Regal Orb',
    "Rogue's Marker",
    'Scroll of Wisdom',
    'Secondary Regrading Lens',
    'Silver Coin',
    'Simple Sextant',
    'Stacked Deck',
    'Tailoring Orb',
    'Tempering Catalyst',
    'Tempering Orb',
    'Turbulent Catalyst',
    'Unstable Catalyst',
    'Vaal Orb',
    'Veiled Chaos Orb',
    "Warlord's Exalted Orb",

    'Alchemy Shard',
    'Alteration Shard',
    'Scroll Fragment',
    'Splinter of Chayula',
    'Splinter of Esh',
    'Splinter of Tul',
    'Splinter of Uul-Netol',
    'Splinter of Xoph',
    "Surveyor's Compass",

    'Vial of Awakening',
    'Vial of Consequence',
    'Vial of Dominance',
    'Vial of Fate',
    'Vial of Sacrifice',
    'Vial of Summoning',
    'Vial of the Ghost',
    'Vial of the Ritual',
    'Vial of Transcendence',

    'Ancient Orb',
    'Ancient Shard',
    'Annulment Shard',
    'Binding Shard',
    'Chaos Shard',
    "Engineer's Orb",
    "Engineer's Shard",
    'Exalted Shard',
    "Harbinger's Orb",
    "Harbinger's Shard",
    'Horizon Shard',
    'Mirror Shard',
    'Orb of Binding',
    'Regal Shard',
    'Transmutation Shard',

    'Aberrant Fossil',
    'Aetheric Fossil',
    'Bloodstained Fossil',
    'Bound Fossil',
    'Corroded Fossil',
    'Dense Fossil',
    'Enchanted Fossil',
    'Encrusted Fossil',
    'Faceted Fossil',
    'Fractured Fossil',
    'Frigid Fossil',
    'Gilded Fossil',
    'Glyphic Fossil',
    'Hollow Fossil',
    'Jagged Fossil',
    'Lucent Fossil',
    'Metallic Fossil',
    'Perfect Fossil',
    'Prismatic Fossil',
    'Pristine Fossil',
    'Sanctified Fossil',
    'Scorched Fossil',
    'Serrated Fossil',
    'Shuddering Fossil',
    'Tangled Fossil',

    'Amber Oil',
    'Azure Oil',
    'Black Oil',
    'Clear Oil',
    'Crimson Oil',
    'Golden Oil',
    'Indigo Oil',
    'Opalescent Oil',
    'Sepia Oil',
    'Silver Oil',
    'Tainted Oil',
    'Teal Oil',
    'Verdant Oil',
    'Violet Oil',

    'Abrasive Catalyst',
    'Accelerating Catalyst',
    'Fertile Catalyst',
    'Imbued Catalyst',
    'Intrinsic Catalyst',
    'Noxious Catalyst',
    'Prismatic Catalyst',
    'Tempering Catalyst',
    'Turbulent Catalyst',
    'Unstable Catalyst',

    'Eternal Orb',
    'Unshaping Orb',
    "Apprentice Cartographer's Seal",
    "Journeyman Cartographer's Seal",
    "Master Cartographer's Seal",
    'Simple Rope Net',
    'Reinforced Rope Net',
    'Strong Rope Net',
    'Simple Iron Net',
    "Tainted Chromatic Orb",
    "Tainted Jeweller's Orb",
    'Reinforced Iron Net',
    'Strong Iron Net',
    'Simple Steel Net',
    'Reinforced Steel Net',
    'Strong Steel Net',
    'Thaumaturgical Net',
    'Necromancy Net',
  ],
  'Dagger': [
    'Glass Shank',
    'Skinning Knife',
    'Stiletto',
    'Flaying Knife',
    'Hollowpoint Dagger',
    'Prong Dagger',
    'Poignard',
    'Pressurised Dagger',
    'Trisula',
    'Gutting Knife',
    'Ambusher',
    'Pneumatic Dagger',
    'Sai',
    'Carving Knife',
    'Boot Knife',
    'Copper Kris',
    'Skean',
    'Flickerflame Blade',
    'Imp Dagger',
    'Butcher Knife',
    'Boot Blade',
    'Golden Kris',
    'Flashfire Blade',
    'Royal Skean',
    'Fiend Dagger',
    'Slaughter Knife',
    'Ezomyte Dagger',
    'Platinum Kris',
    'Imperial Skean',
    'Demon Dagger',
    'Infernal Blade',
    'Goredrill',
    'Bloodplay',
    'Replica Bloodplay',
    'Mightflay',
    'Sanguine Gambol',
    'Goblinedge',
    'Taproot',
    'The Hidden Blade',
    "Replica Ungil's Gauche",
    "Ungil's Gauche",
    'Widowmaker',
    'Heartbreaker',
    'Replica Heartbreaker',
    "Arakaali's Fang",
    'The Consuming Dark',
    'Cold Iron Point',
    'Replica Cold Iron Point',
    'Mark of the Doubting Knight',
    "Bino's Kitchen Knife",
    'Divinarius',
    'White Wind',
    'Vulconus',
  ],

  'Delve Socketable Currency': [],
  'Delve Stackable Socketable Currency': [
    'Potent Alchemical Resonator',
    'Potent Chaotic Resonator',
    'Powerful Alchemical Resonator',
    'Powerful Chaotic Resonator',
    'Prime Alchemical Resonator',
    'Prime Chaotic Resonator',
    'Primitive Alchemical Resonator',
    'Primitive Chaotic Resonator',
  ],

  'Divination Card': [
    "Poisoned Faith",
    "A Chilling Wind",
    "Matryoshka",
    "Soul Quenched",
    "Brother's Gift",
    "The Valkyrie",
    "The Scout",
    "The Rusted Bard",
    "The Price of Devotion",
    "The Forgotten Treasure",
    "The Catch",
    "The Apothecary",
    "Further Invention",
    "Duality",
    "Chasing Risk",
    "Altered Perception",
    "Time-Lost Relic",
    "The Transformation",
    "The Tireless Extractor",
    "The Shieldbearer",
    "The Magma Crab",
    "The Leviathan",
    "The Dungeon Master",
    "The Destination",
    "The Cartographer",
    "The Brawny Battle Mage",
    "The Aspirant",
    "Something Dark",
    "Rebirth and Renewal",
    "Parasitic Passengers",
    "Magnum Opus",
    "Justified Ambition",
    'A Dab of Ink',
    'A Familiar Call',
    "A Fate Worse Than Death",
    'A Modest Request',
    "A Mother's Parting Gift",
    'A Note in the Wind',
    'A Sea of Blue',
    'Abandoned Wealth',
    'Acclimatisation',
    "Akil's Prophecy",
    'Alluring Bounty',
    'Alone in the Darkness',
    'Ambitious Obsession',
    "Anarchy's Price",
    'Arrogance of the Vaal',
    "Assassin's Favour",
    "Atziri's Arsenal",
    'Audacity',
    "Azure Rage",
    "Azyran's Reward",
    'Baited Expectations',
    'Beauty Through Death',
    "Bijoux",
    "Blessing of God",
    'Blind Venture',
    'Boon of Justice',
    'Boon of the First Ones',
    'Boundless Realms',
    "Bowyer's Dream",
    'Broken Promises',
    "Broken Truce",
    "Brother's Stash",
    'Brotherhood in Exile',
    'Brush, Paint and Palette',
    'Buried Treasure',
    'Burning Blood',
    'Call to the First Ones',
    "Cameria's Cut",
    "Cartographer's Delight",
    'Chaotic Disposition',
    "Checkmate",
    'Costly Curio',
    'Council of Cats',
    'Coveted Possession',
    'Cursed Words',
    'Dark Dreams',
    'Dark Temptation',
    "Darker Half",
    'Deadly Joy',
    'Death',
    'Deathly Designs',
    'Dementophobia',
    "Demigod's Wager",
    'Desecrated Virtue',
    "Desperate Crusade",
    'Destined to Crumble',
    "Dialla's Subjugation",
    "Disdain",
    'Divine Justice',
    "Doedre's Madness",
    "Doryani's Epiphany",
    'Draped in Dreams',
    'Dying Anguish',
    'Dying Light',
    'Earth Drinker',
    'Echoes of Love',
    'Emperor of Purity',
    "Emperor's Luck",
    'Etched in Blood',
    "Eternal Bonds",
    'Fateful Meeting',
    'Forbidden Power',
    'Friendship',
    "Gemcutter's Mercy",
    "Gemcutter's Promise",
    'Gift of Asenath',
    'Gift of the Gemling Queen',
    'Glimmer of Hope',
    'Grave Knowledge',
    "Guardian's Challenge",
    'Harmony of Souls',
    'Haunting Shadows',
    'Her Mask',
    'Heterochromia',
    'Hope',
    'House of Mirrors',
    'Hubris',
    'Humility',
    "Hunter's Resolve",
    "Hunter's Reward",
    'Immortal Resolve',
    'Imperial Legacy',
    "Imperfect Memories",
    'Jack in the Box',
    "Keeper's Corruption",
    'Lachrymal Necrosis',
    "Lantador's Lost Love",
    'Last Hope',
    'Left to Fate',
    'Light and Truth',
    'Lingering Remnants',
    'Lost Worlds',
    'Love Through Ice',
    'Loyalty',
    'Lucky Connections',
    'Lucky Deck',
    'Luminous Trove',
    "Lysah's Respite",
    'Mawr Blaidd',
    'Merciless Armament',
    'Might is Right',
    'Mitts',
    'Monochrome',
    'More is Never Enough',
    'No Traces',
    "Nook's Crown",
    'Peaceful Moments',
    'Perfection',
    'Prejudice',
    'Pride Before the Fall',
    'Pride of the First Ones',
    "Prometheus' Armoury",
    'Prosperity',
    'Rain of Chaos',
    'Rain Tempter',
    'Rats',
    'Rebirth',
    'Reckless Ambition',
    'Remembrance',
    "Sambodhi's Vow",
    "Sambodhi's Wisdom",
    'Scholar of the Seas',
    'Seven Years Bad Luck',
    'Shard of Fate',
    "Society's Remorse",
    'Squandered Prosperity',
    'Struck by Lightning',
    'Succor of the Sinless',
    'Terrible Secret of Space',
    'The Academic',
    'The Admirer',
    'The Adventuring Spirit',
    'The Aesthete',
    "The Archmage's Right Hand",
    'The Arena Champion',
    'The Army of Blood',
    'The Artist',
    'The Astromancer',
    'The Avenger',
    'The Awakened',
    'The Bargain',
    'The Battle Born',
    'The Bear Woman',
    'The Beast',
    'The Betrayal',
    'The Bitter Blossom',
    'The Blazing Fire',
    'The Blessing of Moosh',
    'The Body',
    'The Bones',
    'The Breach',
    'The Brittle Emperor',
    'The Cache',
    'The Cacophony',
    'The Calling',
    'The Card Sharp',
    'The Carrion Crow',
    'The Cataclysm',
    'The Catalyst',
    'The Celestial Justicar',
    'The Celestial Stone',
    'The Chains that Bind',
    'The Cheater',
    'The Chosen',
    'The Coming Storm',
    'The Conduit',
    'The Craving',
    'The Cursed King',
    'The Damned',
    'The Dapper Prodigy',
    'The Dark Mage',
    'The Darkest Dream',
    'The Deal',
    'The Deceiver',
    'The Deep Ones',
    'The Demon',
    'The Demoness',
    'The Doctor',
    'The Doppelganger',
    'The Dragon',
    "The Dragon's Heart",
    'The Dreamer',
    'The Dreamland',
    'The Drunken Aristocrat',
    'The Easy Stroll',
    'The Eldritch Decay',
    'The Emptiness',
    'The Encroaching Darkness',
    'The Endless Darkness',
    'The Endurance',
    'The Enlightened',
    'The Enthusiasts',
    'The Escape',
    'The Eternal War',
    'The Ethereal',
    'The Explorer',
    'The Eye of Terror',
    'The Eye of the Dragon',
    'The Fathomless Depths',
    'The Feast',
    'The Fiend',
    'The Fishmonger',
    'The Fletcher',
    "The Flora's Gift",
    'The Fool',
    'The Formless Sea',
    'The Forsaken',
    'The Fox',
    'The Fox in the Brambles',
    'The Gambler',
    'The Garish Power',
    'The Gemcutter',
    'The Gentleman',
    'The Gladiator',
    'The Golden Era',
    'The Greatest Intentions',
    'The Gulf',
    'The Hale Heart',
    'The Harvester',
    'The Harvest',
    'The Hermit',
    'The Heroic Shot',
    'The Hive of Knowledge',
    'The Hoarder',
    'The Hook',
    'The Hunger',
    'The Immortal',
    'The Incantation',
    'The Innocent',
    'The Inoculated',
    'The Insatiable',
    'The Inventor',
    'The Iron Bard',
    'The Jester',
    "The Jeweller's Boon",
    "The Jeweller's Touch",
    'The Journalist',
    'The Journey',
    "The King's Blade",
    "The King's Heart",
    'The Landing',
    'The Last One Standing',
    'The Last Supper',
    'The Lich',
    'The Life Thief',
    'The Lion',
    'The Long Con',
    'The Long Watch',
    'The Lord in Black',
    'The Lord of Celebration',
    'The Lover',
    'The Lunaris Priestess',
    'The Mad King',
    'The Master',
    'The Master Artisan',
    'The Mayor',
    'The Mercenary',
    'The Messenger',
    "The Metalsmith's Gift",
    "The Mind's Eyes",
    'The Mountain',
    'The Nurse',
    'The Oath',
    'The Obscured',
    'The Offering',
    'The Offspring',
    'The Old Man',
    'The One With All',
    'The Opulent',
    'The Pack Leader',
    'The Pact',
    'The Patient',
    'The Penitent',
    'The Poet',
    'The Polymath',
    'The Porcupine',
    'The Price of Loyalty',
    'The Price of Prescience',
    'The Price of Protection',
    'The Primordial',
    'The Professor',
    'The Progeny of Lunaris',
    'The Puzzle',
    'The Queen',
    'The Rabid Rhoa',
    'The Realm',
    'The Risk',
    'The Rite of Elements',
    'The Road to Power',
    'The Ruthless Ceinture',
    'The Sacrifice',
    "The Saint's Treasure",
    "The Samurai's Eye",
    'The Scarred Meadow',
    'The Scavenger',
    'The Scholar',
    'The Seeker',
    'The Sephirot',
    'The Shortcut',
    'The Side Quest',
    'The Sigil',
    'The Siren',
    'The Skeleton',
    'The Soul',
    'The Spark and the Flame',
    'The Spoiled Prince',
    'The Standoff',
    'The Stormcaller',
    'The Strategist',
    'The Summoner',
    'The Sun',
    'The Surgeon',
    'The Surveyor',
    'The Survivalist',
    'The Sustenance',
    "The Sword King's Salute",
    'The Thaumaturgist',
    'The Throne',
    "The Tinkerer's Table",
    'The Tower',
    'The Traitor',
    'The Trial',
    'The Tumbleweed',
    'The Twilight Moon',
    'The Twilight Temple',
    'The Twins',
    'The Tyrant',
    'The Undaunted',
    'The Undisputed',
    'The Unexpected Prize',
    'The Union',
    'The Valkyrie',
    'The Valley of Steel Boxes',
    'The Vast',
    'The Visionary',
    'The Void',
    'The Warden',
    'The Warlord',
    'The Watcher',
    'The Web',
    'The White Knight',
    'The Whiteout',
    'The Wilted Rose',
    'The Wind',
    'The Witch',
    'The Wolf',
    "The Wolf's Legacy",
    "The Wolf's Shadow",
    "The Wolven King's Bite",
    'The Wolverine',
    'The World Eater',
    'The Wrath',
    'The Wretched',
    'Thirst for Knowledge',
    'Three Faces in the Dark',
    'Three Voices',
    'Thunderous Skies',
    'Tranquillity',
    'Treasure Hunter',
    'Triskaidekaphobia',
    'Turn the Other Cheek',
    'Unchained',
    'Underground Forest',
    'Unrequited Love',
    'Vanity',
    'Vile Power',
    "Vinia's Token",
    'Void of the Elements',
    'Volatile Power',
    'Wealth and Power',
    "Winter's Embrace",

    'Man With Bear',
    "Alivia's Grace",
    'Auspicious Ambitions',
    'Divine Beauty',
    'The Wedding Gift',
    'The Insane Cat',
    'Ever-Changing',
    'A Dusty Memory',
    'The Return of the Rat',
    'The Finishing Touch',
  ],
  'Expedition Logbook': [],
  'Flasks': [],
  'Fishing Rod': ['Fishing Rod'],
  'Gems': [
    "Awakened",
    "Vaal"
  ],
  'Gloves': [
    'Iron Gauntlets',
    'Taxing Gauntlets',
    'Plated Gauntlets',
    'Bronze Gauntlets',
    'Steel Gauntlets',
    'Antique Gauntlets',
    'Gruelling Gauntlets',
    'Ancient Gauntlets',
    'Goliath Gauntlets',
    'Vaal Gauntlets',
    'Titan Gauntlets',
    'Debilitation Gauntlets',
    'Spiked Gloves',
    'Rawhide Gloves',
    'Goathide Gloves',
    'Gauche Gloves',
    'Deerskin Gloves',
    'Nubuck Gloves',
    'Eelskin Gloves',
    'Southswing Gloves',
    'Sharkskin Gloves',
    'Shagreen Gloves',
    'Stealth Gloves',
    'Gripped Gloves',
    'Sinistral Gloves',
    'Slink Gloves',
    'Wool Gloves',
    'Leyline Gloves',
    'Velvet Gloves',
    'Silk Gloves',
    'Embroidered Gloves',
    'Aetherwind Gloves',
    'Satin Gloves',
    'Samite Gloves',
    'Conjurer Gloves',
    'Arcanist Gloves',
    'Sorcerer Gloves',
    'Fingerless Silk Gloves',
    'Nexus Gloves',
    'Fishscale Gauntlets',
    'Ironscale Gauntlets',
    'Bronzescale Gauntlets',
    'Steelscale Gauntlets',
    'Serpentscale Gauntlets',
    'Wyrmscale Gauntlets',
    'Hydrascale Gauntlets',
    'Dragonscale Gauntlets',
    'Chain Gloves',
    'Ringmail Gloves',
    'Mesh Gloves',
    'Riveted Gloves',
    'Zealot Gloves',
    'Soldier Gloves',
    'Legion Gloves',
    'Crusader Gloves',
    "Apothecary's Gloves",
    'Wrapped Mitts',
    'Strapped Mitts',
    'Clasped Mitts',
    'Trapper Mitts',
    'Ambush Mitts',
    'Carnal Mitts',
    "Assassin's Mitts",
    'Murder Mitts',
  ],

  'Harvest Object': [],
  'Harvest Infrastructure': [],
  'Harvest Plant Booster': [],
  'Harvest Seed': [],

  'Heist Blueprint': [
    'Blueprint: Bunker',
    'Blueprint: Mansion',
    'Blueprint: Records Office',
    "Blueprint: Smuggler's Den",
    'Blueprint: Underbelly',
    'Blueprint: Laboratory',
    'Blueprint: Prohibited Library',
  ],
  'Heist Brooch': [],
  'Heist Cloak': [],
  'Heist Contract': [
    'Contract: Bunker',
    'Contract: Underbelly',
    'Contract: Mansion',
    'Contract: Records Office',
    "Contract: Smuggler's Den",
    'Contract: Repository',
    'Contract: Tunnels',
    'Contract: Laboratory',
    'Contract: Prohibited Library',
  ],
  'Heist Equipment Reward': [
    'Rough Sharpening Stone',
    'Standard Sharpening Stone',
    'Fine Sharpening Stone',
    'Obsidian Sharpening Stone',
    'Flanged Arrowhead',
    'Fragmenting Arrowhead',
    'Hollowpoint Arrowhead',
    'Precise Arrowhead',
    'Focal Stone',
    'Conduit Line',
    'Aggregator Charm',
    'Burst Band',
  ],
  'Heist Equipment Tool': [
    'Simple Lockpick',
    'Standard Lockpick',
    "Enamel Brooch",
    'Fine Lockpick',
    "Golden Brooch",
    "Hooded Cloak",
    'Master Lockpick',
    'Leather Bracers',
    'Studded Bracers',
    'Runed Bracers',
    'Steel Bracers',
    'Crude Sensing Charm',
    'Fine Sensing Charm',
    'Polished Sensing Charm',
    'Thaumaturgical Sensing Charm',
    'Voltaxic Flashpowder',
    'Trarthan Flashpowder',
    'Azurite Flashpowder',
    'Thaumetic Flashpowder',
    'Crude Ward',
    'Lustrous Ward',
    'Shining Ward',
    'Thaumaturgical Ward',
    'Essential Keyring',
    'Versatile Keyring',
    'Skeleton Keyring',
    'Grandmaster Keyring',
    'Eelskin Sole',
    'Foxhide Sole',
    'Winged Sole',
    'Silkweave Sole',
    'Basic Disguise Kit',
    'Theatre Disguise Kit',
    'Espionage Disguise Kit',
    'Regicide Disguise Kit',
    "Silver Brooch",
    'Steel Drill',
    "Tattered Cloak",
    "Torn Cloak",
    'Flanged Drill',
    'Sulphur Blowtorch',
    'Thaumetic Blowtorch',
  ],
  'Heist Equipment Utility': [],
  'Heist Equipment Weapon': [],
  'Heist Gear': [],
  'Heist Objective': [],
  'Heist Target': [],
  'Heist Tool': [],

  'Helmet': [
    'Iron Hat',
    'Cone Helmet',
    'Barbute Helmet',
    'Close Helmet',
    'Gladiator Helmet',
    'Reaver Helmet',
    'Siege Helmet',
    'Samnite Helmet',
    'Ezomyte Burgonet',
    'Royal Burgonet',
    'Eternal Burgonet',
    'Leather Cap',
    'Tricorne',
    'Leather Hood',
    'Wolf Pelt',
    'Hunter Hood',
    'Noble Tricorne',
    'Ursine Pelt',
    'Silken Hood',
    'Sinner Tricorne',
    'Lion Pelt',
    'Vine Circlet',
    'Iron Circlet',
    'Torture Cage',
    'Tribal Circlet',
    'Bone Circlet',
    'Lunaris Circlet',
    'Steel Circlet',
    'Necromancer Circlet',
    'Solaris Circlet',
    'Mind Cage',
    'Hubris Circlet',
    'Battered Helm',
    'Sallet',
    'Sorrow Mask',
    'Visored Sallet',
    'Gilded Sallet',
    'Secutor Helm',
    'Fencer Helm',
    'Atonement Mask',
    'Lacquered Helmet',
    'Fluted Bascinet',
    'Pig-Faced Bascinet',
    'Nightmare Bascinet',
    'Penitent Mask',
    'Rusted Coif',
    'Soldier Helmet',
    'Imp Crown',
    'Great Helmet',
    'Crusader Helmet',
    'Aventail Helmet',
    'Zealot Helmet',
    'Demon Crown',
    'Great Crown',
    'Magistrate Crown',
    'Prophet Crown',
    'Praetor Crown',
    'Bone Helmet',
    'Archdemon Crown',
    'Scare Mask',
    'Plague Mask',
    'Gale Crown',
    'Iron Mask',
    'Festival Mask',
    'Golden Mask',
    'Raven Mask',
    'Callous Mask',
    'Winter Crown',
    'Regicide Mask',
    'Harlequin Mask',
    'Vaal Mask',
    'Deicide Mask',
    'Blizzard Crown',
    'Runic Helm',
    'Runic Crest',
    'Runic Crown',
  ],
  'Hideout Doodad': [],
  'Hybrid Flask': [
    'Small Hybrid Flask',
    'Medium Hybrid Flask',
    'Large Hybrid Flask',
    'Colossal Hybrid Flask',
    'Sacred Hybrid Flask',
    'Hallowed Hybrid Flask',
  ],
  'Incubator': [
    'Abyssal Incubator',
    'Blighted Incubator',
    "Cartographer's Incubator",
    "Celestial Armoursmith's Incubator",
    "Celestial Blacksmith's Incubator",
    "Celestial Jeweller's Incubator",
    'Decadent Incubator',
    "Diviner's Incubator",
    'Eldritch Incubator',
    'Enchanted Incubator',
    'Feral Incubator',
    'Fine Incubator',
    'Foreboding Incubator',
    'Fossilised Incubator',
    'Fragmented Incubator',
    "Gemcutter's Incubator",
    "Geomancer's Incubator",
    'Infused Incubator',
    'Maddening Incubator',
    'Morphing Incubator',
    'Mysterious Incubator',
    'Obscured Incubator',
    'Ornate Incubator',
    'Otherworldly Incubator',
    'Primal Incubator',
    'Singular Incubator',
    'Skittering Incubator',
    "Thaumaturge's Incubator",
    'Time-Lost Incubator',
    'Whispering Incubator',
  ],
  'Incursion Item': [
    'Flashpowder Keg',
    'Stone of Passage',
    'Vial of Summoning',
    'Vial of Fate',
    'Vial of Consequence',
    'Vial of Dominance',
    'Vial of the Ritual',
    'Vial of Awakening',
    'Vial of Transcendence',
    'Vial of the Ghost',
    'Vial of Sacrifice',
    'Sacrificial Heart',
    'Soul Catcher',
    'String of Servitude',
    'Tempered Mind',
    'Tempered Spirit',
    'Shadowstitch',
    "Apep's Slumber",
    "Architect's Hand",
    "Coward's Chains",
    'Dance of the Offered',
    'Mask of the Spirit Drinker',
    'Story of the Vaal',
    'Vial of Awakening',
    "Apep's Slumber",
    "Apep's Supremacy",
    'Vial of Consequence',
    "Coward's Chains",
    "Coward's Legacy",
    'Vial of Dominance',
    "Architect's Hand",
    "Slavedriver's Hand",
    'Vial of Fate',
    'Story of the Vaal',
    'Fate of the Vaal',
    'Vial of Summoning',
    'Mask of the Spirit Drinker',
    'Mask of the Stitched Demon',
    'Vial of the Ritual',
    'Dance of the Offered',
    'Omeyocan',
    'Vial of Transcendence',
    'Tempered Flesh',
    'Transcendent Flesh',
    'Tempered Spirit',
    'Transcendent Spirit',
    'Tempered Mind',
    'Transcendent Mind',
    'Vial of Sacrifice',
    'Sacrificial Heart',
    "Zerphi's Heart",
    'Vial of the Ghost',
    'Soul Catcher',
    'Soul Ripper',
  ],
  'Jewels': [
    'Cobalt Jewel',
    'Crimson Jewel',
    'Viridian Jewel',
    'Cluster Jewel',
    'Small Cluster Jewel',
    'Medium Cluster Jewel',
    'Large Cluster Jewel',
    'Undying Flesh Talisman',
  ],

  'Labyrinth Item': [],
  'Labyrinth Map Item': [],
  'Labyrinth Trinket': [
    'Bane of the Loyal',
    'Cogs of Disruption',
    'Cube Of Absorption',
    'Heart of the Gargoyle',
    'Orb of Elemental Dispersion',
    'Portal Shredder',
    'Rod of Detonation',
    'Sand of Eternity',
  ],

  'Leaguestone': [
    'Ambush Leaguestone',
    '1	Next Area will contain a Strongbox',
    'Ambush (Hidden)Corrupted',
    'Anarchy Leaguestone',
    '11	Next Area will contain a Rogue Exile',
    'Anarchy (Hidden)Corrupted',
    'Beyond Leaguestone',
    '5	Slaying Enemies close together in next Area will attract monsters from Beyond this realm',
    'Beyond (Hidden)Corrupted',
    'Bloodlines Leaguestone',
    '10	Magic Monster Packs in next Area will each have a Bloodline Mod',
    'Next Area will contain additional Magic Monsters',
    'Bloodlines (Hidden)Corrupted',
    'Breach Leaguestone',
    'Domination Leaguestone',
    'Essence Leaguestone',
    'Invasion Leaguestone',
    'Nemesis Leaguestone',
    'Onslaught Leaguestone',
    'Perandus Leaguestone',
    'Prophecy Leaguestone',
    'Rampage Leaguestone',
    'Talisman Leaguestone',
    'Tempest Leaguestone',
    'Torment Leaguestone',
    'Warbands Leaguestone',
  ],
  'Life Flask': [
    'Small Life Flask',
    'Medium Life Flask',
    'Large Life Flask',
    'Greater Life Flask',
    'Grand Life Flask',
    'Giant Life Flask',
    'Colossal Life Flask',
    'Sacred Life Flask',
    'Hallowed Life Flask',
    'Sanctified Life Flask',
    'Divine Life Flask',
    'Eternal Life Flask',
  ],
  'Mana Flask': [
    'Small Mana Flask',
    'Medium Mana Flask',
    'Large Mana Flask',
    'Greater Mana Flask',
    'Grand Mana Flask',
    'Giant Mana Flask',
    'Colossal Mana Flask',
    'Sacred Mana Flask',
    'Hallowed Mana Flask',
    'Sanctified Mana Flask',
    'Divine Mana Flask',
    'Eternal Mana Flask',
    "Doedre's Elixir",
    "Zerphi's Last Breath",
    "Lavianga's Spirit",
    "Replica Lavianga's Spirit",
  ],
  'Map': [
    'Beach Map',
    'Dungeon Map',
    'Graveyard Map',
    'Lookout Map',
    'Alleyways Map',
    'Arid Lake Map',
    'Desert Map',
    'Flooded Mine Map',
    'Marshes Map',
    'Pen Map',
    'Arcade Map',
    'Burial Chambers Map',
    'Cage Map',
    'Cells Map',
    'Excavation Map',
    'Iceberg Map',
    'Leyline Map',
    'Peninsula Map',
    'Port Map',
    'Fungal Hollow Map',
    "Esh's Domain",
    "Tul's Domain",
    "Xoph's Domain",
    'The Apex of Sacrifice',
    'Canyon Map',
    'Chateau Map',
    'City Square Map',
    'Courthouse Map',
    'Glacier Map',
    'Grotto Map',
    'Lighthouse Map',
    'The Perandus Manor',
    'Relic Chambers Map',
    'Strand Map',
    'Whakawairua Tuahu',
    'Volcano Map',
    'Ancient City Map',
    'Barrows Map',
    'Channel Map',
    'Conservatory Map',
    'Haunted Mansion Map',
    'Ivory Temple Map',
    'Maze Map',
    'Spider Lair Map',
    'Sulphur Vents Map',
    'Toxic Sewer Map',
    'The Beachhead',
    'Academy Map',
    'Atoll Map',
    'Maelström of Chaos',
    'Ashen Wood Map',
    'Cemetery Map',
    'Hallowed Ground',
    'Fields Map',
    'Jungle Valley Map',
    'Mausoleum Map',
    'Phantasmagoria Map',
    'Thicket Map',
    'Underground Sea Map',
    "Oba's Cursed Trove",
    'Wharf Map',
    'Arachnid Nest Map',
    'Bazaar Map',
    'Bone Crypt Map',
    "Olmec's Sanctum",
    'Coral Ruins Map',
    'Dunes Map',
    'Pillars of Arun',
    'Gardens Map',
    'Lava Chamber Map',
    'Ramparts Map',
    'Residence Map',
    'Underground River Map',
    "Caer Blaidd, Wolfpack's Den",
    'Armoury Map',
    'Courtyard Map',
    'The Vinktar Square',
    'Geode Map',
    'Infested Valley Map',
    'Laboratory Map',
    'Mineral Pools Map',
    'Mud Geyser Map',
    'Overgrown Ruin Map',
    'Shore Map',
    'Mao Kun',
    'The Pale Court',
    'Tropical Island Map',
    'Untainted Paradise',
    'Vaal Pyramid Map',
    'Vaults of Atziri',
    'Arena Map',
    'Estuary Map',
    'Moon Temple Map',
    'The Twilight Temple',
    'Museum Map',
    'The Putrid Cloister',
    'Plateau Map',
    'Scriptorium Map',
    'Sepulchre Map',
    'Temple Map',
    "Poorjoy's Asylum",
    'Tower Map',
    'Vault Map',
    'Waste Pool Map',
    'Arachnid Tomb Map',
    'Belfry Map',
    'Bog Map',
    'Cursed Crypt Map',
    "The Coward's Trial",
    'Orchard Map',
    'Pier Map',
    'Precinct Map',
    'Shipyard Map',
    'Siege Map',
    'The Beachhead',
    'Wasteland Map',
    'Colonnade Map',
    'Coves Map',
    'Factory Map',
    'Mesa Map',
    'Lair Map',
    'Pit Map',
    'Primordial Pool Map',
    'Promenade Map',
    'Hall of Grandmasters',
    'Spider Forest Map',
    'Waterways Map',
    'Castle Ruins Map',
    'Crystal Ore Map',
    'Defiled Cathedral Map',
    'Necropolis Map',
    'Death and Taxes',
    'Overgrown Shrine Map',
    "Acton's Nightmare",
    'Racecourse Map',
    'Summit Map',
    'Primordial Blocks Map',
    'Villa Map',
    'Arsenal Map',
    'Caldera Map',
    'Core Map',
    "Chayula's Domain",
    'Desert Spring Map',
    'Ghetto Map',
    'Malformation Map',
    'Park Map',
    'Shrine Map',
    'Terrace Map',
    'The Alluring Abyss',
    'Acid Caverns Map',
    'Colosseum Map',
    'Crimson Temple Map',
    'Dark Forest Map',
    'Dig Map',
    'Palace Map',
    'Plaza Map',
    'Basilica Map',
    'Carcass Map',
    'Lava Lake Map',
    'Reef Map',
    'Sunken City Map',
    'The Beachhead',
    'Forge of the Phoenix Map',
    'Lair of the Hydra Map',
    'Maze of the Minotaur Map',
    'Pit of the Chimera Map',
    'Vaal Temple Map',
    "The Shaper's Realm",
    'Crater Map',
  ],
  'Map Fragments': [
    'Blood-filled Vessel',
    "Chayula's Breachstone",
    "Chayula's Charged Breachstone",
    "Chayula's Enriched Breachstone",
    "Chayula's Pure Breachstone",
    'Craicic Lure',
    'Dedication to the Goddess',
    'Divine Vessel',
    "Eber's Key",
    "Esh's Breachstone",
    "Esh's Charged Breachstone",
    "Esh's Enriched Breachstone",
    "Esh's Pure Breachstone",
    'Farric Lure',
    'Fenumal Lure',
    'Fragment of Constriction',
    'Fragment of Emptiness',
    'Fragment of Enslavement',
    'Fragment of Eradication',
    'Fragment of Knowledge',
    'Fragment of Purification',
    'Fragment of Shape',
    'Fragment of Terror',
    'Fragment of the Chimera',
    'Fragment of the Hydra',
    'Fragment of the Minotaur',
    'Fragment of the Phoenix',
    'Gift to the Goddess',
    'Gilded Abyss Scarab',
    'Gilded Ambush Scarab',
    'Gilded Bestiary Scarab',
    'Gilded Blight Scarab',
    'Gilded Breach Scarab',
    'Gilded Cartography Scarab',
    'Gilded Divination Scarab',
    'Gilded Elder Scarab',
    'Gilded Harbinger Scarab',
    'Gilded Legion Scarab',
    'Gilded Metamorph Scarab',
    'Gilded Perandus Scarab',
    'Gilded Reliquary Scarab',
    'Gilded Shaper Scarab',
    'Gilded Sulphite Scarab',
    'Gilded Torment Scarab',
    "Inya's Key",
    'Mortal Grief',
    'Mortal Hope',
    'Mortal Ignorance',
    'Mortal Rage',
    'Offering to the Goddess',
    'Polished Abyss Scarab',
    'Polished Ambush Scarab',
    'Polished Bestiary Scarab',
    'Polished Blight Scarab',
    'Polished Breach Scarab',
    'Polished Cartography Scarab',
    'Polished Divination Scarab',
    'Polished Elder Scarab',
    'Polished Harbinger Scarab',
    'Polished Legion Scarab',
    'Polished Metamorph Scarab',
    'Polished Perandus Scarab',
    'Polished Reliquary Scarab',
    'Polished Shaper Scarab',
    'Polished Sulphite Scarab',
    'Polished Torment Scarab',
    'Rusted Abyss Scarab',
    'Rusted Ambush Scarab',
    'Rusted Bestiary Scarab',
    'Rusted Blight Scarab',
    'Rusted Breach Scarab',
    'Rusted Cartography Scarab',
    'Rusted Divination Scarab',
    'Rusted Elder Scarab',
    "Rusted Expedition Scarab",
    'Rusted Harbinger Scarab',
    'Rusted Legion Scarab',
    'Rusted Metamorph Scarab',
    'Rusted Perandus Scarab',
    'Rusted Reliquary Scarab',
    'Rusted Shaper Scarab',
    'Rusted Sulphite Scarab',
    'Rusted Torment Scarab',
    'Sacred Blossom',
    'Sacrifice at Dawn',
    'Sacrifice at Dusk',
    'Sacrifice at Midnight',
    'Sacrifice at Noon',
    'Saqawine Lure',
    'Simulacrum',
    "The Maven's Writ",
    'Timeless Eternal Emblem',
    'Timeless Karui Emblem',
    'Timeless Maraketh Emblem',
    'Timeless Templar Emblem',
    'Timeless Vaal Emblem',
    'to the Goddess',
    'Tribute to the Goddess',
    "Tul's Breachstone",
    "Tul's Charged Breachstone",
    "Tul's Enriched Breachstone",
    "Tul's Pure Breachstone",
    "Uul-Netol's Breachstone",
    "Uul-Netol's Charged Breachstone",
    "Uul-Netol's Enriched Breachstone",
    "Uul-Netol's Pure Breachstone",
    "Volkuur's Key",
    'Winged Abyss Scarab',
    'Winged Ambush Scarab',
    'Winged Bestiary Scarab',
    'Winged Blight Scarab',
    'Winged Breach Scarab',
    'Winged Cartography Scarab',
    'Winged Divination Scarab',
    'Winged Elder Scarab',
    'Winged Harbinger Scarab',
    'Winged Legion Scarab',
    'Winged Metamorph Scarab',
    'Winged Perandus Scarab',
    'Winged Reliquary Scarab',
    'Winged Shaper Scarab',
    'Winged Sulphite Scarab',
    'Winged Torment Scarab',
    "Xoph's Breachstone",
    "Xoph's Charged Breachstone",
    "Xoph's Enriched Breachstone",
    "Xoph's Pure Breachstone",
    "Yriel's Key",
  ],
  "Memory": [],
  'Metamorphosis DNA': [
    'Metamorph Brain',
    'Metamorph Eye',
    'Metamorph Lung',
    'Metamorph Heart',
    'Metamorph Liver',
  ],
  'Misc Map Item': [
    'Chronicle of Atzoatl',
    'Inscribed Ultimatum',
    "Maven's Invitation",
    "Maven's Invitation: The Atlas",
    "Maven's Invitation: Glennach Cairns",
    "Maven's Invitation: Haewark Hamlet",
    "Maven's Invitation: Lex Ejoris",
    "Maven's Invitation: Lex Proxima",
    "Maven's Invitation: Lira Arthain",
    "Maven's Invitation: New Vastir",
    "Maven's Invitation: The Feared",
    "Maven's Invitation: The Forgotten",
    "Maven's Invitation: The Formed",
    "Maven's Invitation: The Hidden",
    "Maven's Invitation: The Twisted",
    "Maven's Invitation: Tirn's End",
    "Maven's Invitation: Valdo's Rest",
    "Polaric Invitation",
    'Vaal Reliquary Key',
    'Ancient Reliquary Key',
    'Timeworn Reliquary Key',
    "Writhing Invitation"
  ],
  'One Hand Axe': [
    'Rusted Hatchet',
    'Jade Hatchet',
    'Boarding Axe',
    'Cleaver',
    'Broad Axe',
    'Arming Axe',
    'Decorative Axe',
    'Maltreatment Axe',
    'Spectral Axe',
    'Etched Hatchet',
    'Jasper Axe',
    'Tomahawk',
    'Wrist Chopper',
    'War Axe',
    'Chest Splitter',
    'Disapprobation Axe',
    'Ceremonial Axe',
    'Wraith Axe',
    'Engraved Hatchet',
    'Karui Axe',
    'Siege Axe',
    'Reaver Axe',
    'Butcher Axe',
    'Vaal Hatchet',
    'Royal Axe',
    'Infernal Axe',
    'Psychotic Axe',
    'Runic Hatchet',
  ],
  'One Hand Mace': [
    'Driftwood Club',
    'Tribal Club',
    'Spiked Club',
    'Stone Hammer',
    'War Hammer',
    'Bladed Mace',
    'Ceremonial Mace',
    'Flare Mace',
    'Dream Mace',
    'Wyrm Mace',
    'Petrified Club',
    'Barbed Club',
    'Rock Breaker',
    'Battle Hammer',
    'Flanged Mace',
    'Crack Mace',
    'Ornate Mace',
    'Phantom Mace',
    'Dragon Mace',
    'Ancestral Club',
    'Tenderizer',
    'Gavel',
    'Legion Hammer',
    'Pernach',
    'Auric Mace',
    'Nightmare Mace',
    'Behemoth Mace',
    'Boom Mace',
    'Gorebreaker',
    'Brightbeak',
    "Lavianga's Wisdom",
    'Flesh-Eater',
    'Clayshaper',
    'Frostbreath',
    'Replica Frostbreath',
    "Cameria's Avarice",
    "Cameria's Maul",
    'Mjölner',
    'Callinellus Malleus',
    'Nebuloch',
  ],
  'One Hand Sword': [
    "Charan's Sword",
    'Rusted Sword',
    'Copper Sword',
    'Sabre',
    'Broad Sword',
    'War Sword',
    'Ancient Sword',
    'Elegant Sword',
    'Fickle Spiritblade',
    'Dusk Blade',
    'Hook Sword',
    'Variscite Blade',
    'Cutlass',
    'Baselard',
    'Battle Sword',
    'Elder Sword',
    'Capricious Spiritblade',
    'Graceful Sword',
    'Twilight Blade',
    'Grappler',
    'Gemstone Sword',
    'Corsair Sword',
    'Gladius',
    'Legion Sword',
    'Vaal Blade',
    'Eternal Sword',
    'Midnight Blade',
    'Anarchic Spiritblade',
    'Tiger Hook',
    'Golden Blade',
    'Energy Blade',
    'Rusted Spike',
    'Whalebone Rapier',
    'Battered Foil',
    'Basket Rapier',
    'Jagged Foil',
    'Antique Rapier',
    'Elegant Foil',
    'Thorn Rapier',
    'Smallsword',
    'Wyrmbone Rapier',
    'Burnished Foil',
    'Estoc',
    'Serrated Foil',
    'Primeval Rapier',
    'Fancy Foil',
    'Apex Rapier',
    'Courtesan Sword',
    'Dragonbone Rapier',
    'Tempered Foil',
    'Pecoraro',
    'Spiraled Foil',
    'Vaal Rapier',
    'Jewelled Foil',
    'Harpy Rapier',
    'Dragoon Sword',
    'Oni-Goroshi',
    'Redbeak',
    'The Princess',
    'Replica Tempestuous Steel',
    'The Tempestuous Steel',
    "Lakishu's Blade",
    'The Goddess Scorned',
    'Ephemeral Edge',
    'Severed in Sleep',
    'Innsbury Edge',
    'Replica Innsbury Edge',
    'Prismatic Eclipse',
    'Fate of the Vaal',
    'Story of the Vaal',
    'Ichimonji',
    'Scaeva',
    'The Iron Mass',
    'The Redblade',
    "Hyaon's Fury",
    'The Rippling Thoughts',
    'The Saviour',
    'The Surging Thoughts',
    'Rebuke of the Vaal',
    'Varunastra',
    'Beltimber Blade',
    'Dreamfeather',
    'Grelwood Shank',
    'Replica Dreamfeather',
    "Ahn's Might",
    'Razor of the Seventh Sun',
    "Rigwald's Command",
    'United in Dream',
    'Blood of Summer',
    "Demigod's Authority",
    'Dreadbeak',
    'The Goddess Unleashed',
    'The Goddess Bound',
    'Aurumvorax',
    "Fidelitas' Spike",
    "Ewar's Mirage",
    "Daresso's Passion",
    'Paradoxica',
    'Replica Paradoxica',
    "Cospri's Malice",
  ],
  'Pantheon Soul': [],
  "Piece": [],
  'Quest': [
    'The Kiss Goodnight',
    'The Nameless Play',
    'Alchemical Supplies',
    "Alira's Amulet",
    'Allflame',
    'Ammonite Glyph',
    'Ankh of Eternity',
    'Baffling Blueprints',
    'Baleful Gem',
    'Basilisk Acid',
    "Bestel's Manuscript",
    'Black Venom',
    'Blackguard Personnel Files',
    'Bottled Storm',
    'Bust of Gaius Sentari',
    'Bust of Hector Titucius',
    'Bust of Marceus Lioneye',
    'Calendar of Fortune',
    'Census Records',
    "Chitus' Plum",
    'Confront Nashta',
    'Contract: A Matter of Honour',
    'Contract: Flying False Colours',
    'Contract: Follow the Paper Trail',
    "Contract: Hyrri's Gift",
    "Contract: Isla's Designs",
    "Contract: Isla's Prototypes",
    "Contract: Slaver's Revenge",
    'Contract: The Finest Costumes',
    'Contract: The Nameless Play',
    'Contract: The Negotiation',
    'Contract: The Rescue',
    'Contract: Trial Run',
    'Decanter Spiritus',
    "Deshret's Banner",
    'Elixir of Allure',
    "Enoch's Tags",
    'Eye of Conquest',
    'Eyes of Zeal',
    'Firefly',
    'Fleet Orders',
    'Fumarole Tar',
    'Golden Hand',
    'Golden Page',
    'Haliotis Glyph',
    "Hapihapi's Charm",
    "Hinekora's Hair",
    'Infernal Talc',
    "Karst's Lockpicks",
    "Kishara's Star",
    "Kraityn's Amulet",
    "Malachai's Entrails",
    "Malachai's Heart",
    "Malachai's Lungs",
    "Maligaro's Map",
    "Maligaro's Spike",
    'Master Key',
    "Maven's Invitation: Glennach Cairns (1)",
    "Maven's Invitation: Haewark Hamlet (1)",
    "Maven's Invitation: Lex Ejoris (1)",
    "Maven's Invitation: Lex Proxima (1)",
    "Maven's Invitation: Lira Arthain (1)",
    "Maven's Invitation: New Vastir (1)",
    "Maven's Invitation: Tirn's End (1)",
    "Maven's Invitation: Valdo's Rest (1)",
    'Medicine Chest',
    'Memory Fragment I',
    'Memory Fragment II',
    'Memory Fragment III',
    'Memory Fragment IV',
    'Memory Fragment IX',
    'Memory Fragment V',
    'Memory Fragment VI',
    'Memory Fragment VII',
    'Memory Fragment VIII',
    'Memory Fragment X',
    'Memory Fragment XI',
    'Memory Fragment XII',
    'Memory Fragment XIII',
    'Memory Fragment XIV',
    'Memory Fragment XV',
    'Miasmeter',
    'Moon Orb',
    "Nashta's War Journal",
    "Oak's Amulet",
    'Obsidian Key',
    'Pile of Inexplicable Junk',
    'Poisoned Lockpick',
    'Ribbon Spool',
    'Roseus Glyph',
    'Sekhema Feather',
    'Sewer Keys',
    'Sign of Purity',
    'Silver Locket',
    "Slaver's Records",
    "Solerai's Spear",
    'Storm Blade',
    'Sun Orb',
    'Templar Uniforms',
    'Thaumetic Emblem',
    'Thaumetic Sulphite',
    'The Apex',
    'The Black Flag',
    'The Blood Idol',
    'The Book of Jamanra',
    'The Eye of Desire',
    'The Eye of Fury',
    "The Maven's Beacon",
    "The Shaper's Key",
    'The Staff of Purity',
    'The Teardrop',
    'The Thought Extractor',
    'The Vox Twins',
    "Tibbs' Wealth",
    "Tolman's Bracelet",
    'Tower Key',
    'Trarthan Powder',
    "Tukohama's Tooth",
    "Tullina's Engagement Ring",
    "Valako's Jaw",
    'Vault Key',
    "Viridi's Finger",
    'Wings of Vastiri',
  ],
  'Quiver': [
    'Two-Point Arrow Quiver',
    'Serrated Arrow Quiver',
    'Sharktooth Arrow Quiver',
    'Blunt Arrow Quiver',
    'Fire Arrow Quiver',
    'Broadhead Arrow Quiver',
    'Penetrating Arrow Quiver',
    'Spike-Point Arrow Quiver',
    'Artillery Quiver',
    'Rugged Quiver',
    'Cured Quiver',
    'Conductive Quiver',
    'Heavy Quiver',
    'Light Quiver',
    'Serrated Arrow Quiver',
    'Ornate Quiver',
  ],
  'Relic': [],
  'Rings': [
    'Bone Ring',
    'Breach Ring',
    'Coral Ring',
    'Iron Ring',
    'Paua Ring',
    'Unset Ring',
    'Sapphire Ring',
    'Topaz Ring',
    'Ruby Ring',
    'Diamond Ring',
    'Gold Ring',
    'Moonstone Ring',
    'Two-Stone Ring',
    'Two-Stone Ring',
    'Two-Stone Ring',
    'Cogwork Ring',
    'Geodesic Ring',
    'Amethyst Ring',
    'Prismatic Ring',
    'Iolite Ring',
    'Cerulean Ring',
    'Opal Ring',
    'Steel Ring',
    'Vermillion Ring',
    'Golden Hoop',
    'Jet Ring',
    'Blackheart',
    "Doedre's Damning",
    "Kaom's Sign",
    'Perandus Signet',
    "Replica Doedre's Damning",
    "Malachai's Artifice",
    "Replica Malachai's Artifice",
    'Pyre',
    'Emberwake',
    "Mokou's Embrace",
    'Replica Emberwake',
    'Andvarius',
    "Berek's Grip",
    "Berek's Pass",
    "Berek's Respite",
    'Call of the Brotherhood',
    'Heartbound Loop',
    'Kikazaru',
    "Replica Tasalio's Sign",
    "Tasalio's Sign",
    'Praxis',
    'Timeclasp',
    'Bloodboil',
    'Dream Fragments',
    'Le Heup of All',
    'Mark of Submission',
    'Gifts from Above',
    "Ngamahu's Sign",
    "Lori's Lantern",
    "Shavronne's Revelation",
    'The Taming',
    "The Warden's Brand",
    "Thief's Torment",
    "Kaom's Way",
    "Angler's Plait",
    'Essence Worm',
    'Fated End',
    "Valako's Sign",
    'Valyrium',
    'Astral Projector',
    "Warrior's Legacy",
    'Brinerot Mark',
    'Mutewind Seal',
    'Redblade Band',
    'The Highwayman',
    'Replica Voideye',
    "Sibyl's Lament",
    'Vivinsect',
    'Voideye',
    'Death Rush',
    'Voidheart',
    "Ahkeli's Meadow",
    "Ahkeli's Mountain",
    "Ahkeli's Valley",
    'Blackflame',
    'Icefang Orbit',
    "Precursor's Emblem",
    "Putembo's Meadow",
    "Putembo's Mountain",
    "Putembo's Valley",
    "Rigwald's Crest",
    "Uzaza's Meadow",
    "Uzaza's Mountain",
    "Uzaza's Valley",
    'Venopuncture',
    'Circle of Anguish',
    'Circle of Fear',
    'Circle of Guilt',
    'Circle of Nostalgia',
    'Circle of Regret',
    'Profane Proxy',
    'Winterweave',
    'Rotblood Promise',
    'Storm Secret',
    "Romira's Banquet",
    'The Pariah',
    'Timetwist',
    'Triumvirate Authority',
    'Triumvirate Authority',
    "Ventor's Gamble",
    'Snakepit',
    "Ming's Heart",
    'The Hungry Loop',
    'Mark of the Elder',
    'Mark of the Shaper',
    'Stormfire',
    "Demigod's Eye",
    'Band of the Victor',
    'Circle of Nostalgia',
    'Circle of Regret',
    'Circle of Anguish',
    'Circle of Fear',
    'Circle of Guilt',
  ],
  'Rune Dagger': [
    'Carving Knife',
    'Boot Knife',
    'Copper Kris',
    'Skean',
    'Flickerflame Blade',
    'Imp Dagger',
    'Butcher Knife',
    'Boot Blade',
    'Golden Kris',
    'Flashfire Blade',
    'Royal Skean',
    'Fiend Dagger',
    'Slaughter Knife',
    'Ezomyte Dagger',
    'Platinum Kris',
    'Imperial Skean',
    'Demon Dagger',
    'Infernal Blade',
  ],
  'Sanctified Relic': [],
  'Sceptre': [
    'Driftwood Sceptre',
    'Darkwood Sceptre',
    'Bronze Sceptre',
    'Quartz Sceptre',
    'Iron Sceptre',
    'Ochre Sceptre',
    'Ritual Sceptre',
    'Oscillating Sceptre',
    'Shadow Sceptre',
    'Grinning Fetish',
    'Horned Sceptre',
    'Sekhem',
    'Crystal Sceptre',
    'Lead Sceptre',
    'Blood Sceptre',
    'Royal Sceptre',
    'Stabilising Sceptre',
    'Abyssal Sceptre',
    'Stag Sceptre',
    'Karui Sceptre',
    "Tyrant's Sekhem",
    'Opal Sceptre',
    'Platinum Sceptre',
    'Vaal Sceptre',
    'Carnal Sceptre',
    'Void Sceptre',
    'Alternating Sceptre',
    'Sambar Sceptre',
    'Axiom Perpetuum',
    'Spine of the First Claimant',
    "Brutus' Lead Sprinkler",
    'Bitterdream',
    'Replica Bitterdream',
    'The Dark Seer',
    "Earendel's Embrace",
    "Replica Earendel's Embrace",
    "Nycta's Lantern",
    'The Supreme Truth',
    'Cerberus Limb',
    'The Black Cane',
    "Death's Hand",
    'Sign of the Sin Eater',
    'Balefire',
    'Singularity',
    'Doon Cuebiyari',
    "Yaomac's Accord",
    'Breath of the Council',
    'Augyre',
    "Mon'tregul's Grasp",
    'Nebulis',
    'Replica Nebulis',
    "Doryani's Catalyst",
  ],
  'Shield': [
    'Splintered Tower Shield',
    'Corroded Tower Shield',
    'Rawhide Tower Shield',
    'Cedar Tower Shield',
    'Copper Tower Shield',
    'Exothermic Tower Shield',
    'Reinforced Tower Shield',
    'Painted Tower Shield',
    'Buckskin Tower Shield',
    'Mahogany Tower Shield',
    'Bronze Tower Shield',
    'Magmatic Tower Shield',
    'Girded Tower Shield',
    'Crested Tower Shield',
    'Shagreen Tower Shield',
    'Ebony Tower Shield',
    'Ezomyte Tower Shield',
    'Colossal Tower Shield',
    'Heat-attuned Tower Shield',
    'Pinnacle Tower Shield',
    'Goathide Buckler',
    'Pine Buckler',
    'Painted Buckler',
    'Hammered Buckler',
    'War Buckler',
    'Endothermic Buckler',
    'Gilded Buckler',
    'Oak Buckler',
    'Enameled Buckler',
    'Corrugated Buckler',
    'Battle Buckler',
    'Polar Buckler',
    'Golden Buckler',
    'Ironwood Buckler',
    'Lacquered Buckler',
    'Vaal Buckler',
    'Crusader Buckler',
    'Imperial Buckler',
    'Cold-attuned Buckler',
    'Twig Spirit Shield',
    'Yew Spirit Shield',
    'Bone Spirit Shield',
    'Tarnished Spirit Shield',
    'Jingling Spirit Shield',
    'Exhausting Spirit Shield',
    'Brass Spirit Shield',
    'Walnut Spirit Shield',
    'Ivory Spirit Shield',
    'Ancient Spirit Shield',
    'Chiming Spirit Shield',
    'Subsuming Spirit Shield',
    'Thorium Spirit Shield',
    'Lacewood Spirit Shield',
    'Fossilised Spirit Shield',
    'Vaal Spirit Shield',
    'Harmonic Spirit Shield',
    'Titanium Spirit Shield',
    'Transfer-attuned Spirit Shield',
    'Rotted Round Shield',
    'Fir Round Shield',
    'Studded Round Shield',
    'Scarlet Round Shield',
    'Splendid Round Shield',
    'Maple Round Shield',
    'Spiked Round Shield',
    'Crimson Round Shield',
    'Baroque Round Shield',
    'Teak Round Shield',
    'Spiny Round Shield',
    'Cardinal Round Shield',
    'Elegant Round Shield',
    'Plank Kite Shield',
    'Linden Kite Shield',
    'Reinforced Kite Shield',
    'Layered Kite Shield',
    'Ceremonial Kite Shield',
    'Etched Kite Shield',
    'Steel Kite Shield',
    'Laminated Kite Shield',
    'Angelic Kite Shield',
    'Branded Kite Shield',
    'Champion Kite Shield',
    'Mosaic Kite Shield',
    'Archon Kite Shield',
    'Spiked Bundle',
    'Driftwood Spiked Shield',
    'Alloyed Spiked Shield',
    'Burnished Spiked Shield',
    'Ornate Spiked Shield',
    'Redwood Spiked Shield',
    'Compound Spiked Shield',
    'Polished Spiked Shield',
    'Sovereign Spiked Shield',
    'Alder Spiked Shield',
    'Ezomyte Spiked Shield',
    'Mirrored Spiked Shield',
    'Supreme Spiked Shield',
    'Lycosidae',
    'Trolltimber Spire',
    "Titucius' Span",
    'Redblade Banner',
    "Chernobog's Pillar",
    "Replica Tukohama's Fortress",
    "Tukohama's Fortress",
    'The Anticipation',
    'The Surrender',
    "Ahn's Heritage",
    "Lioneye's Remorse",
    'Magna Eclipsis',
    'Crest of Perandus',
    'Kaltenhalt',
    'Kaltensoul',
    'Chalice of Horrors',
    'Thirst for Horrors',
    'Mutewind Pennant',
    "Great Old One's Ward",
    "Atziri's Mirror",
    'Mistwall',
    'Replica Mistwall',
    'Thousand Teeth Temu',
    "Atziri's Reflection",
    'Brinerot Flag',
    'Matua Tupuna',
    'Light of Lunaris',
    "Sentari's Answer",
    "Kongming's Stratagem",
    'The Eternal Apple',
    "Esh's Mirror",
    'Manastorm',
    "Apep's Slumber",
    "Apep's Supremacy",
    "Esh's Visage",
    'Whakatutuki o Matua',
    "Malachai's Loop",
    'Bitterbind Point',
    'Rathpith Globe',
    'Wheel of the Stormsail',
    "The Deep One's Hide",
    'Shattershard',
    "Daresso's Courage",
    'The Ghastly Theatre',
    'Vix Lunaris',
    'Springleaf',
    'The Oak',
    "Emperor's Vigilance",
    "Mahuxotl's Machination",
    "Replica Victario's Charity",
    "Victario's Charity",
    "Saffell's Frame",
    'Aegis Aurora',
    'Rise of the Phoenix',
    'Broken Faith',
    'Invictus Solaris',
    'Prism Guardian',
    'The Immortal Will',
    'The Unshattered Will',
    'Unyielding Flame',
    'Glitterdisc',
    "Maligaro's Lens",
    "Zeel's Amplifier",
    "Qotra's Regulator",
    'Perepiteia',
    'Font of Thunder',
    "Leper's Alms",
    'Jaws of Agony',
  ],
  'Stackable Currency': ["Lycia's Invocation"],
  'Staff': [
    'Gnarled Branch',
    'Long Staff',
    'Royal Staff',
    'Transformer Staff',
    'Crescent Staff',
    'Woodful Staff',
    'Quarterstaff',
    'Reciprocation Staff',
    'Highborn Staff',
    'Moon Staff',
    'Primordial Staff',
    'Lathi',
    'Imperial Staff',
    'Battery Staff',
    'Eclipse Staff',
    'Iron Staff',
    'Coiled Staff',
    'Vile Staff',
    'Military Staff',
    'Serpentine Staff',
    'Potentiality Rod',
    'Foul Staff',
    'Ezomyte Staff',
    'Maelström Staff',
    'Judgement Staff',
    'Eventuality Rod',
    'Fencoil',
    'Replica Blood Thorn',
    'Replica Fencoil',
    'The Blood Thorn',
    'The Stormheart',
    'Mirebough',
    'Martyr of Innocence',
    'Femurs of the Saints',
    'The Stormwall',
    'The Searing Touch',
    'Agnerod East',
    'Agnerod North',
    'Agnerod South',
    'Agnerod West',
    'The Enmity Divine',
    'The Yielding Mortality',
    "Witchhunter's Judgment",
    'Dying Breath',
    'Pillar of the Caged God',
    'Realmshaper',
    "Xirgil's Crank",
    'The Whispering Ice',
    'Realm Ender',
    'Tremor Rod',
    'Sire of Shards',
    'Cane of Unravelling',
    'Soulwrest',
    'The Fulcrum',
    'Disintegrator',
    'Duskdawn',
    'Replica Duskdawn',
    "Taryn's Shiver",
    "Atziri's Rule",
    'Cane of Kulemak',
    "Hegemony's Era",
    'Pledge of Hands',
    'The Grey SpireGnarled Branch',
    'Primitive Staff',
    'Long Staff',
    'Royal Staff',
    'Crescent Staff',
    'Woodful Staff',
    'Quarterstaff',
    'Reciprocation Staff',
    'Highborn Staff',
    'Moon Staff',
    'Primordial Staff',
    'Lathi',
    'Imperial Staff',
    'Battery Staff',
    'Eclipse Staff',
    'Coiled Staff',
    'Capacity Rod',
    'Vile Staff',
    'Military Staff',
    'Serpentine Staff',
    'Potentiality Rod',
    'Foul Staff',
    'Ezomyte Staff',
    'Maelström Staff',
    'Judgement Staff',
    'Eventuality Rod',
    'Fencoil',
    'Replica Blood Thorn',
    'Replica Fencoil',
    'The Blood Thorn',
    'The Stormheart',
    'Mirebough',
    'Martyr of Innocence',
    'Femurs of the Saints',
    'The Stormwall',
    'The Searing Touch',
    'Agnerod East',
    'Agnerod North',
    'Agnerod South',
    'Agnerod West',
    'The Enmity Divine',
    'The Yielding Mortality',
    "Witchhunter's Judgment",
    'Dying Breath',
    'Pillar of the Caged God',
    'Realmshaper',
    "Xirgil's Crank",
    'The Whispering Ice',
    'Realm Ender',
    'Tremor Rod',
    'Sire of Shards',
    'Cane of Unravelling',
    'Soulwrest',
    'The Fulcrum',
    'Disintegrator',
    'Duskdawn',
    'Replica Duskdawn',
    "Taryn's Shiver",
    "Atziri's Rule",
    'Cane of Kulemak',
    "Hegemony's Era",
    'Pledge of Hands',
    'The Grey Spire',
  ],
  'Support Skill Gem': [
    'Added Cold Damage Support',
    'Additional Accuracy Support',
    'Advanced Traps Support',
    'Arrow Nova Support',
    'Awakened Added Cold Damage Support',
    'Awakened Arrow Nova Support',
    'Awakened Cast On Critical Strike Support',
    'Awakened Chain Support',
    'Awakened Cold Penetration Support',
    'Awakened Deadly Ailments Support',
    'Awakened Fork Support',
    'Awakened Greater Multiple Projectiles Support',
    'Awakened Swift Affliction Support',
    'Awakened Vicious Projectiles Support',
    'Awakened Void Manipulation Support',
    'Barrage Support',
    'Blind Support',
    'Block Chance Reduction Support',
    'Cast On Critical Strike Support',
    'Cast on Death Support',
    'Chain Support',
    'Chance to Flee Support',
    'Chance to Poison Support',
    'Charged Traps Support',
    'Close Combat Support',
    'Cluster Traps Support',
    'Cold Penetration Support',
    'Critical Strike Affliction Support',
    'Culling Strike Support',
    'Deadly Ailments Support',
    'Enhance Support',
    'Faster Attacks Support',
    'Faster Projectiles Support',
    'Fork Support',
    'Greater Multiple Projectiles Support',
    'Greater Volley Support',
    'Hypothermia Support',
    'Ice Bite Support',
    'Impale Support',
    'Lesser Multiple Projectiles Support',
    'Mana Leech Support',
    'Mark on Hit Support',
    'Mirage Archer Support',
    'Multiple Traps Support',
    'Nightblade Support',
    'Onslaught Support',
    'Pierce Support',
    'Point Blank Support',
    'Second Wind Support',
    'Slower Projectiles Support',
    'Swift Affliction Support',
    'Swift Assembly Support',
    'Trap and Mine Damage Support',
    'Trap Support',
    'Vicious Projectiles Support',
    'Vile Toxins Support',
    'Void Manipulation Support',
    'Volley Support',
    'Withering Touch Support',
    'Added Fire Damage Support',
    'Ancestral Call Support',
    'Arrogance Support',
    'Awakened Added Fire Damage Support',
    'Awakened Ancestral Call Support',
    'Awakened Brutality Support',
    'Awakened Burning Damage Support',
    'Awakened Elemental Damage With Attacks Support',
    'Awakened Fire Penetration Support',
    'Awakened Generosity Support',
    'Awakened Melee Physical Damage Support',
    'Awakened Melee Splash Support',
    'Awakened Multistrike Support',
    'Ballista Totem Support',
    'Bloodlust Support',
    'Bloodthirst Support',
    'Brutality Support',
    'Burning Damage Support',
    'Cast on Melee Kill Support',
    'Cast when Damage Taken Support',
    'Chance to Bleed Support',
    'Cold to Fire Support',
    'Cruelty Support',
    'Damage on Full Life Support',
    'Elemental Damage with Attacks Support',
    'Empower Support',
    'Endurance Charge on Melee Stun Support',
    'Fire Penetration Support',
    'Fist of War Support',
    'Fortify Support',
    'Generosity Support',
    'Increased Duration Support',
    'Inspiration Support',
    'Iron Grip Support',
    'Iron Will Support',
    'Knockback Support',
    'Less Duration Support',
    'Life Gain on Hit Support',
    'Life Leech Support',
    'Lifetap Support',
    'Maim Support',
    'Melee Physical Damage Support',
    'Melee Splash Support',
    'Multiple Totems Support',
    'Multistrike Support',
    'Pulverise Support',
    'Rage Support',
    'Ruthless Support',
    'Shockwave Support',
    'Spell Totem Support',
    'Stun Support',
    'Urgent Orders Support',
    'Added Chaos Damage Support',
    'Added Lightning Damage Support',
    'Arcane Surge Support',
    'Archmage Support',
    'Awakened Added Chaos Damage Support',
    'Awakened Added Lightning Damage Support',
    'Awakened Blasphemy Support',
    'Awakened Cast While Channelling Support',
    'Awakened Controlled Destruction Support',
    'Awakened Elemental Focus Support',
    'Awakened Hextouch Support',
    'Awakened Increased Area Of Effect Support',
    'Awakened Lightning Penetration Support',
    'Awakened Minion Damage Support',
    'Awakened Spell Cascade Support',
    'Awakened Spell Echo Support',
    'Awakened Unbound Ailments Support',
    'Awakened Unleash Support',
    'Blasphemy Support',
    'Blastchain Mine Support',
    'Bonechill Support',
    'Cast when Stunned Support',
    'Cast while Channelling Support',
    'Charged Mines Support',
    'Combustion Support',
    'Concentrated Effect Support',
    'Controlled Destruction Support',
    'Decay Support',
    'Efficacy Support',
    'Elemental Army Support',
    'Elemental Focus Support',
    'Elemental Penetration Support',
    'Elemental Proliferation Support',
    'Energy Leech Support',
    'Enlighten Support',
    'Faster Casting Support',
    'Feeding Frenzy Support',
    'Hextouch Support',
    'High-Impact Mine Support',
    'Ignite Proliferation Support',
    'Immolate Support',
    'Impending Doom Support',
    'Increased Area of Effect Support',
    'Increased Critical Damage Support',
    'Increased Critical Strikes Support',
    'Infernal Legion Support',
    'Infused Channelling Support',
    'Innervate Support',
    'Intensify Support',
    'Item Rarity Support',
    'Lightning Penetration Support',
    'Meat Shield Support',
    'Minefield Support',
    'Minion Damage Support',
    'Minion Life Support',
    'Minion Speed Support',
    'Physical to Lightning Support',
    'Pinpoint Support',
    'Power Charge On Critical Support',
    'Predator Support',
    'Spell Cascade Support',
    'Spell Echo Support',
    'Summon Phantasm Support',
    'Swiftbrand Support',
    'Trinity Support',
    'Unbound Ailments Support',
    'Unleash Support',
    'Item Quantity Support',
  ],
  'Trinket': [],
  'Two Hand Axe': [
    'Stone Axe',
    'Jade Chopper',
    'Woodsplitter',
    'Poleaxe',
    'Double Axe',
    'Gilded Axe',
    'Prime Cleaver',
    'Shadow Axe',
    'Dagger Axe',
    'Jasper Chopper',
    'Timber Axe',
    'Headsman Axe',
    'Labrys',
    'Honed Cleaver',
    'Noble Axe',
    'Abyssal Axe',
    'Karui Chopper',
    'Talon Axe',
    'Sundering Axe',
    'Ezomyte Axe',
    'Vaal Axe',
    'Despot Axe',
    'Void Axe',
    'Apex Cleaver',
    'Fleshripper',
  ],
  'Two Hand Mace': [
    'Driftwood Maul',
    '1	20	10-16	1.30	5.00%	16.9	30% increased Stun Duration on Enemies',
    'Tribal Maul',
    'Mallet',
    'Sledgehammer',
    'Jagged Maul',
    'Brass Maul',
    'Blunt Force Condenser',
    'Fright Maul',
    'Morning Star',
    'Totemic Maul',
    'Great Mallet',
    'Steelhead',
    'Spiny Maul',
    'Crushing Force Magnifier',
    'Plated Maul',
    'Dread Maul',
    'Solar Maul',
    'Karui Maul',
    'Colossus Mallet',
    'Piledriver',
    'Meatgrinder',
    'Imperial Maul',
    'Terror Maul',
    'Coronal Maul',
    'Impact Force Propagator',
    "Hrimnor's Hymn",
    'Quecholli',
    "Geofri's Baptism",
    "Hrimnor's Dirge",
    'Chober Chaber',
    'Replica Trypanon',
    'Trypanon',
    "Jorrhast's Blacksteel",
    'Voidhome',
    'Marohi Erqi',
    'Chaber Cairn',
    "Geofri's Devotion",
    'Panquetzaliztli',
    'Brain Rattler',
    'Tidebreaker',
    "Kongor's Undying Rage",
    "Replica Kongor's Undying Rage",
  ],
  'Two Hand Sword': [
    'Corroded Blade',
    'Longsword',
    'Bastard Sword',
    'Two-Handed Sword',
    'Etched Greatsword',
    'Ornate Sword',
    'Rebuking Blade',
    'Spectral Sword',
    'Curved Blade',
    'Butcher Sword',
    'Footman Sword',
    'Highland Blade',
    'Engraved Greatsword',
    'Blasting Blade',
    'Tiger Sword',
    'Wraith Sword',
    'Lithe Blade',
    "Headman's Sword",
    'Reaver Sword',
    'Ezomyte Blade',
    'Vaal Greatsword',
    'Lion Sword',
    'Infernal Sword',
    'Banishing Blade',
    'Exquisite Blade',
    'Shiversting',
    'Edge of Madness',
    "Queen's Decree",
    "Queen's Escape",
    "Rigwald's Charge",
    'Terminus Est',
    'Hiltless',
    'The Dancing Dervish',
    "Kondo's Pride",
    'Doomsower',
    'The Dancing Duo',
    "Oro's Sacrifice",
    "Replica Oro's Sacrifice",
    'Starforge',
    'Voidforge',
  ],
  'Unarmed': [],
  'Unique Fragment': [],
  'Unique Shard': [],
  'Unique Shard Base': [],
  'Utility Flasks': [
    'Quicksilver Flask',
    'Bismuth Flask',
    'Amethyst Flask',
    'Ruby Flask',
    'Sapphire Flask',
    'Topaz Flask',
    'Aquamarine Flask',
    'Diamond Flask',
    'Granite Flask',
    'Jade Flask',
    'Quartz Flask',
    'Sulphur Flask',
    'Basalt Flask',
    'Iron Flask',
    'Silver Flask',
    'Stibnite Flask',
    'The Wise Oak',
    "Sin's Rebirth",
    'Coruscating Elixir',
    'Taste of Hate',
    "Kiara's Determination",
    "Coralito's Signature",
    'Forbidden Taste',
    "Lion's Roar",
    'Soul Catcher',
    'Soul Ripper',
    'Bottled Faith',
    'Replica Sorrow of the Divine',
    'The Overflowing Chalice',
    'The Sorrow of the Divine',
    'Rotgut',
    'Cinderswallow Urn',
    'Witchfire Brew',
    "Atziri's Promise",
    'Dying Sun',
    "Replica Rumi's Concoction",
    "Rumi's Concoction",
    'Vessel of Vinktar',
  ],
  'Vault Key': [
    "Forgotten Reliquary Key",
    "Visceral Reliquary Key",
    "Shiny Reliquary Key",
    "Archive Reliquary Key",
    "Oubliette Reliquary Key",
    "Cosmic Reliquary Key",
    "Decaying Reliquary Key",
    "Voidborn Reliquary Key",
  ],
  'Wand': [
    'Convening Wand',
    'Driftwood Wand',
    "Goat's Horn",
    'Carved Wand',
    'Quartz Wand',
    'Spiraled Wand',
    'Assembler Wand',
    'Sage Wand',
    'Pagan Wand',
    "Faun's Horn",
    'Engraved Wand',
    'Calling Wand',
    'Crystal Wand',
    'Serpent Wand',
    'Congregator Wand',
    'Omen Wand',
    'Heathen Wand',
    "Demon's Horn",
    'Imbued Wand',
    'Opal Wand',
    'Tornado Wand',
    'Prophecy Wand',
    'Accumulator Wand',
    'Profane Wand',
    'Convoking Wand',
    'Lifesprig',
    "Abberath's Horn",
    'Storm Prison',
    "The Poet's Pen",
    'Ashcaller',
    'Relic of the Pact',
    'Reverberation Rod',
    'Tulborn',
    'Replica Twyzel',
    'Shade of Solaris',
    'Twyzel',
    'Amplification Rod',
    'Midnight Bargain',
    'Replica Midnight Bargain',
    'Eclipse Solaris',
    'Obliteration',
    'Moonsorrow',
    "Apep's Rage",
    'Corona Solaris',
    "Piscator's Vigil",
    'Replica Tulfall',
    'Shimmeron',
    'Tulfall',
    'Void Battery',
  ],
  'Warstaff': [
    'Iron Staff',
    'Coiled Staff',
    'Capacity Rod',
    'Vile Staff',
    'Military Staff',
    'Serpentine Staff',
    'Potentiality Rod',
    'Foul Staff',
    'Ezomyte Staff',
    'Maelström Staff',
    'Judgement Staff',
    'Eventuality Rod',
    'Dying Breath',
    'Pillar of the Caged God',
    'Realmshaper',
    "Xirgil's Crank",
    'The Whispering Ice',
    'Realm Ender',
    'Tremor Rod',
    'Sire of Shards',
    'Cane of Unravelling',
    'Soulwrest',
    'The Fulcrum',
    'Disintegrator',
    'Duskdawn',
    'Replica Duskdawn',
    "Taryn's Shiver",
    "Atziri's Rule",
    'Cane of Kulemak',
    "Hegemony's Era",
    'Pledge of Hands',
    'The Grey Spire',
  ],
  'Other': ['Tainted'],
});

export default baseTypes;
