const content = JSON.stringify({
  rules: {
    Blocks: ['Show', 'Hide', 'Minimal'],
    SocketFilters: [
      {
        property: 'LinkedSockets',
        instance: 'OperatorNum',
        defaultVal: { operator: '>', numValues: [4] },
        min: '2',
        max: '6',
      },
      {
        property: 'SocketGroup',
        instance: 'OperatorNumColors',
        defaultVal: {
          operator: '>=',
          numValues: [5],
          sockets: { R: 1, G: 3, B: 0, A: 0, D: 0, W: 0 },
        },
        min: '2',
        max: '6',
      },
    ],

    Miscellaneous: [
      {
        instance: 'OperatorNumMultiple',
        defaultVal: {
          operator: '>=',
          numValues: [2],
          textValues: ['"of Haast"', '"of Tzteosh"', '"of Ephij"'],
        },
        property: 'HasExplicitMod',
        options: 'ExplicitMods',
        min: '1',
        max: '6',
      },
//      {
//        instance: 'Multiple',
//        defaultVal: { values: ['Toxic'] },
//        property: 'ArchnemesisMod',
//        options: 'ArchnemesisMods',
//      },
    ],
//    Actions: [
//      {
//        property: 'PlayAlertSound',
//        instance: 'NumericTwo',
//        defaultVal: { values: [1, 100] },
//        min: '1',
//        max: '16',
//      },
//    ],
  },
  operators: ['=', '!', '<=', '>=', '<', '>', '=='],
  GemQualityType: ['Superior', 'Divergent', 'Anomalous', 'Phantasmal'],
  ArchnemesisMods: [
    'Steel-infused',
    'Flameweaver',
    'Stormweaver',
    'Frostweaver',
    'Gargantuan',
    'Hasted',
    'Chaosweaver',
    'Arcane Buffer',
    'Echoist',
    'Sentinel',
    'Splinterer',
    'Deadeye',
    'Electrocuting',
    'Vampiric',
    'Overcharged',
    'Flame Strider',
    'Frost Strider',
    'Storm Strider',
    'Ice Prison',
    'Entangler',
    'Toxic',
    'Treant Horde',
    'Bloodletter',
    'Bonebreaker',
    'Juggernaut',
    'Soul Conduit',
    'Consecrator',
    'Frenzied',
    'Assassin',
    'Necromancer',
    'Hexer',
    'Mirror Image',
    'Spirit Walkers',
    'Union of Souls',
    'Storm Herald',
    'Prismatic',
    'Bombardier',
    'Malediction',
    'Rejuvenating',
    'Executioner',
    'Temporal Bubble',
    'Soul Eater',
    'Corpse Detonator',
    'Magma Barrier',
    'Incendiary',
    'Crystal Skinned',
    'Mana Siphoner',
    'Heralding Minions',
    'Benevolent Guardian',
    'Final Gasp',
    'Berserker',
    'Drought Bringer',
    'Corruptor',
    'Empowered Elements',
    'Effigy',
    'Empowering Minions',
    'Permafrost',
    'Trickster',
    'Opulent',
    'Lunaris-touched',
    'Solaris-touched',
    'Arakaali-touched',
    'Brine King-touched',
    'Tukohama-touched',
    'Abberath-touched',
    'Shakari-touched',
    'Innocence-touched',
    'Kitava-touched',
  ],
  ExplicitMods: ['of Haast', 'of Tzteosh', 'of Ephij'],
  Rarity: ['Normal', 'Magic', 'Rare', 'Unique'],
});

export default content;
